### ISSUE TITLE
FileNotFoundError: No such file or directory: README.rst

### ISSUE THREAD

**Issue by SebCorbin** [arteria/django-compat#44]
```
$ ./bin/pip --version
pip 8.0.2 from /webapps/planexo/lib/python3.4/site-packages (python 3.4)

$ ./bin/pip install django-compat
Collecting django-compat
  Using cached django-compat-1.0.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-build-1wztbpt3/django-compat/setup.py", line 33, in <module>
        long_description=read('README.rst')
      File "/tmp/pip-build-1wztbpt3/django-compat/setup.py", line 17, in read
        return open(get_path(fname)).read()
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-1wztbpt3/django-compat/README.rst'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1wztbpt3/django-compat/setup.py", line 36, in <module>
        long_description=read('README.md')
      File "/tmp/pip-build-1wztbpt3/django-compat/setup.py", line 17, in read
        return open(get_path(fname)).read()
      File "/webapps/planexo/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 8678: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1wztbpt3/django-compat
```

**Comment by jvamvas** [comment]
Thank you for reporting this issue, @SebCorbin. I have tried to fix the errors with the latest release. Please report back whether they still occur in your environment.
